services:
  - type: web
    name: ulmform
    env: python
    buildCommand: bash -x ./build_cura.sh
    startCommand: gunicorn app:app
    plan: free
    envVars:
      - key: FLASK_ENV
        value: production
