services:
  - type: web
    name: ulmform
    env: python
    buildCommand: |
      chmod +x build_cura.sh
      ./build_cura.sh
      pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free
    envVars:
      - key: FLASK_ENV
        value: production
