services:
  - type: web
    name: ulmform
    env: python
    plan: free
    buildCommand: |
      apt-get update && apt-get install -y cmake git build-essential
      git clone https://github.com/Ultimaker/CuraEngine.git
      cd CuraEngine
      cmake .
      make
      mv CuraEngine ../bin/CuraEngine
      pip install -r ../requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
