services:
  - type: web
    name: ulmform
    env: python
    buildCommand: bash build_cura.sh
    startCommand: gunicorn app:app
    plan: free
    envVars:
      - key: FLASK_ENV
        value: production
      - key: RENDER_PYTHON_BUILD_POETRY
        value: false
